# Generated by Django 5.2 on 2025-06-27 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_alter_festival_options_remove_festival_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festival',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='festivalattendance',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='festivalbookmark',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='festivalcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='festivalfact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='festivalfeedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='festivalmedia',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='festivalfact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='festivalfact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='festivalmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='festivalmedia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
