# Generated by Django 5.2 on 2025-06-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255, verbose_name='Verb')),
                ('target', models.CharField(blank=True, max_length=255, null=True, verbose_name='Target')),
                ('action_object', models.CharField(blank=True, max_length=255, null=True, verbose_name='Action Object')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('read', models.BooleanField(default=False, verbose_name='Read')),
                ('type', models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('support', 'Support'), ('review', 'Review'), ('generic', 'Generic')], default='generic', max_length=50, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-timestamp'],
            },
        ),
    ]
