# Generated by Django 5.2 on 2025-06-27 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0003_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='context_object_id',
            new_name='object_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='context_object_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('festival_new', 'New Festival'), ('festival_attendance', 'Festival Attendance'), ('festival_feedback', 'Festival Feedback'), ('tutor_booked', 'Tutor/Guide Booked'), ('assignment', 'Assignment'), ('quiz', 'Quiz'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('payout_success', 'Payout Success'), ('custom', 'Custom')], max_length=32),
        ),
    ]
