# Generated by Django 5.2 on 2025-06-28 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_userquizprogress_quiz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at']},
        ),
    ]
