# Generated by Django 5.2 on 2025-06-16 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('tourism_status', models.BooleanField(default=False, verbose_name='Tourism Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='villages/', verbose_name='Photo')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='Population')),
                ('language', models.CharField(blank=True, max_length=100, verbose_name='Language')),
                ('history', models.TextField(blank=True, verbose_name='History')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocalSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('site_type', models.CharField(choices=[('museum', 'Museum'), ('monument', 'Monument'), ('park', 'Park')], max_length=50, verbose_name='Site Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localsites', to='villages.village', verbose_name='Village')),
            ],
            options={
                'verbose_name': 'Local Site',
                'verbose_name_plural': 'Local Sites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('attraction_type', models.CharField(choices=[('natural', 'Natural'), ('cultural', 'Cultural'), ('historical', 'Historical')], max_length=50, verbose_name='Attraction Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('tourist_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Tourist Rating')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='villages.village', verbose_name='Village')),
            ],
            options={
                'verbose_name': 'Attraction',
                'verbose_name_plural': 'Attractions',
                'ordering': ['name'],
            },
        ),
    ]
