# Generated by Django 5.2 on 2025-06-06 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('tourism_status', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='villages/')),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('history', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocalSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site_type', models.CharField(choices=[('museum', 'Museum'), ('monument', 'Monument'), ('park', 'Park')], max_length=50)),
                ('description', models.TextField()),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localsites', to='villages.village')),
            ],
            options={
                'verbose_name': 'Local Site',
                'verbose_name_plural': 'Local Sites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attraction_type', models.CharField(choices=[('natural', 'Natural'), ('cultural', 'Cultural'), ('historical', 'Historical')], max_length=50)),
                ('description', models.TextField()),
                ('tourist_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='villages.village')),
            ],
            options={
                'verbose_name': 'Attraction',
                'verbose_name_plural': 'Attractions',
                'ordering': ['name'],
            },
        ),
    ]
