# Generated by Django 5.2 on 2025-06-26 11:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localsite',
            name='village',
        ),
        migrations.AlterModelOptions(
            name='village',
            options={},
        ),
        migrations.RemoveField(
            model_name='village',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='village',
            name='history',
        ),
        migrations.RemoveField(
            model_name='village',
            name='language',
        ),
        migrations.RemoveField(
            model_name='village',
            name='location',
        ),
        migrations.RemoveField(
            model_name='village',
            name='photo',
        ),
        migrations.AddField(
            model_name='village',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villages_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='village',
            name='art_crafts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='village',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='village',
            name='cultural_highlights',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='village',
            name='department',
            field=models.CharField(default='Unknown', help_text='Department in the West Region', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='village',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='learn_more',
            field=models.TextField(blank=True, help_text='What can you learn about this village?'),
        ),
        migrations.AddField(
            model_name='village',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='main_languages',
            field=models.CharField(blank=True, help_text='Comma-separated list', max_length=255),
        ),
        migrations.AddField(
            model_name='village',
            name='traditional_foods',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='village',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='population',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='tourism_status',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Unknown')], default='unknown', max_length=16),
        ),
        migrations.CreateModel(
            name='VillageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='villages.village')),
            ],
        ),
        migrations.CreateModel(
            name='VillageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='villages/images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='villages.village')),
            ],
        ),
        migrations.DeleteModel(
            name='Attraction',
        ),
        migrations.DeleteModel(
            name='LocalSite',
        ),
    ]
