# Generated by Django 5.2 on 2025-06-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villages', '0002_remove_localsite_village_alter_village_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='village',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='villagecomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='villageimage',
            options={'ordering': ['-id']},
        ),
    ]
