# Generated by Django 5.2 on 2025-06-16 21:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='Date')),
                ('new_users', models.PositiveIntegerField(default=0, verbose_name='New Users')),
                ('active_users', models.PositiveIntegerField(default=0, verbose_name='Active Users')),
                ('total_bookings', models.PositiveIntegerField(default=0, verbose_name='Total Bookings')),
                ('total_tour_bookings', models.PositiveIntegerField(default=0, verbose_name='Total Tour Bookings')),
                ('total_tutor_bookings', models.PositiveIntegerField(default=0, verbose_name='Total Tutor Bookings')),
                ('total_guide_bookings', models.PositiveIntegerField(default=0, verbose_name='Total Guide Bookings')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='Total Reviews')),
                ('total_reports', models.PositiveIntegerField(default=0, verbose_name='Total Reports')),
            ],
            options={
                'verbose_name': 'Daily Site Statistic',
                'verbose_name_plural': 'Daily Site Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DashboardStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.CharField(max_length=100, unique=True, verbose_name='Stat Name')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Value')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Dashboard Stat',
                'verbose_name_plural': 'Dashboard Stats',
                'ordering': ['stat_name'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='Average Rating')),
                ('total_feedback', models.PositiveIntegerField(default=0, verbose_name='Total Feedback')),
                ('positive_feedback', models.PositiveIntegerField(default=0, verbose_name='Positive Feedback')),
                ('negative_feedback', models.PositiveIntegerField(default=0, verbose_name='Negative Feedback')),
            ],
            options={
                'verbose_name': 'Feedback Summary',
                'verbose_name_plural': 'Feedback Summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GuideBookingStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Region')),
                ('bookings_count', models.PositiveIntegerField(default=0, verbose_name='Bookings Count')),
            ],
            options={
                'verbose_name': 'Guide Booking Statistic',
                'verbose_name_plural': 'Guide Booking Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=20, verbose_name='Notification Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
            ],
            options={
                'verbose_name': 'System Notification',
                'verbose_name_plural': 'System Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourBookingStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('tour_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tour Type')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('bookings_count', models.PositiveIntegerField(default=0, verbose_name='Bookings Count')),
            ],
            options={
                'verbose_name': 'Tour Booking Statistic',
                'verbose_name_plural': 'Tour Booking Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TutorBookingStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('bookings_count', models.PositiveIntegerField(default=0, verbose_name='Bookings Count')),
            ],
            options={
                'verbose_name': 'Tutor Booking Statistic',
                'verbose_name_plural': 'Tutor Booking Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view_festival', 'Viewed Festival'), ('view_tourism', 'Viewed Tourism Spot'), ('book_tour', 'Booked Tour'), ('book_tutor', 'Booked Tutor'), ('book_guide', 'Booked Guide'), ('post_review', 'Posted Review'), ('submit_report', 'Submitted Report'), ('other', 'Other')], max_length=50, verbose_name='Action')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
