# Generated by Django 5.2 on 2025-06-06 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guidebookingstatistic',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_booking_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tourbookingstatistic',
            unique_together={('date', 'tour_type', 'location')},
        ),
        migrations.AddField(
            model_name='tutorbookingstatistic',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_booking_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='guidebookingstatistic',
            unique_together={('date', 'guide', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='tutorbookingstatistic',
            unique_together={('date', 'tutor', 'subject')},
        ),
    ]
