# Generated by Django 5.2 on 2025-06-26 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysitestatistics',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dashboardstat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='feedbacksummary',
            options={},
        ),
        migrations.AlterModelOptions(
            name='guidebookingstatistic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='systemnotification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tourbookingstatistic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tutorbookingstatistic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='guidebookingstatistic',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tourbookingstatistic',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tutorbookingstatistic',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dailysitestatistics',
            name='total_reports',
        ),
        migrations.RemoveField(
            model_name='dashboardstat',
            name='description',
        ),
        migrations.AddField(
            model_name='dailysitestatistics',
            name='total_events',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysitestatistics',
            name='total_festivals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysitestatistics',
            name='active_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysitestatistics',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='dailysitestatistics',
            name='new_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysitestatistics',
            name='total_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysitestatistics',
            name='total_guide_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysitestatistics',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysitestatistics',
            name='total_tour_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysitestatistics',
            name='total_tutor_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboardstat',
            name='label',
            field=models.CharField(blank=True, default='Label', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dashboardstat',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dashboardstat',
            name='stat_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dashboardstat',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='feedbacksummary',
            name='average_rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='feedbacksummary',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='feedbacksummary',
            name='negative_feedback',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feedbacksummary',
            name='positive_feedback',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feedbacksummary',
            name='total_feedback',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guidebookingstatistic',
            name='bookings_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guidebookingstatistic',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='guidebookingstatistic',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guidebookingstatistic',
            name='region',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='system_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tourbookingstatistic',
            name='bookings_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tourbookingstatistic',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tourbookingstatistic',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourbookingstatistic',
            name='tour_type',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorbookingstatistic',
            name='bookings_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutorbookingstatistic',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tutorbookingstatistic',
            name='subject',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorbookingstatistic',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='description',
            field=models.TextField(blank=True, default='No description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('stat', 'Statistic'), ('map', 'Map'), ('calendar', 'Calendar'), ('weather', 'Weather'), ('reviews', 'Reviews'), ('featured', 'Featured'), ('gallery', 'Gallery'), ('leaderboard', 'Leaderboard'), ('phrase', 'Language Phrase'), ('event', 'Event'), ('custom', 'Custom'), ('assignments', 'Assignments'), ('sessions', 'Sessions'), ('payments', 'Payments'), ('support', 'Support'), ('quizzes', 'Quizzes'), ('reports', 'Reports'), ('notifications', 'Notifications')], max_length=30)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
