# Generated by Django 5.2 on 2025-06-16 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('guide', 'Touristic Guide'), ('tutor', 'Tutor'), ('site', 'Tourist Site'), ('festival', 'Festival'), ('village', 'Village')], max_length=50, verbose_name='Target Type')),
                ('target_id', models.PositiveIntegerField(verbose_name='Target ID')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Rating')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.review', verbose_name='Parent Review')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
