# Generated by Django 5.2 on 2025-06-06 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('guide', 'Touristic Guide'), ('tutor', 'Tutor'), ('site', 'Tourist Site'), ('festival', 'Festival'), ('village', 'Village')], max_length=50)),
                ('target_id', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.review')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
