# Generated by Django 5.2 on 2025-06-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('tutoring', 'Tutoring'), ('tour_guide', 'Tour Guide')], max_length=50, verbose_name='Session Type')),
                ('topic_or_location', models.CharField(help_text='Topic for tutoring or location for guide session', max_length=255, verbose_name='Topic or Location')),
                ('scheduled_time', models.DateTimeField(verbose_name='Scheduled Time')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Duration (minutes)')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Is Confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Custom Session',
                'verbose_name_plural': 'Custom Sessions',
                'ordering': ['-scheduled_time'],
            },
        ),
    ]
