# Generated by Django 5.2 on 2025-06-16 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customsession',
            name='learner_or_visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attending_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Learner or Visitor'),
        ),
        migrations.AddField(
            model_name='customsession',
            name='tutor_or_guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Tutor or Guide'),
        ),
    ]
