# Generated by Django 5.2 on 2025-06-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentmethod_rename_user_booking_learner_or_visitor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['name'], 'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AlterModelOptions(
            name='paymentreceipt',
            options={'ordering': ['-issued_at'], 'verbose_name': 'Payment Receipt', 'verbose_name_plural': 'Payment Receipts'},
        ),
        migrations.AlterModelOptions(
            name='payout',
            options={'ordering': ['-date'], 'verbose_name': 'Payout', 'verbose_name_plural': 'Payouts'},
        ),
    ]
