# Generated by Django 5.2 on 2025-06-26 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_alter_festival_options_remove_festival_image_and_more'),
        ('tourism', '0003_hostingfamilyexperience_sharedtouristmedia_and_more'),
        ('tutorials', '0001_initial'),
        ('villages', '0002_remove_localsite_village_alter_village_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialstep',
            name='tutorial',
        ),
        migrations.AlterModelOptions(
            name='tutorial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tutorialcategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='language',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tutorialcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tutorialcategory',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='attraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorials', to='tourism.touristicattraction'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='content',
            field=models.TextField(default='No content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='festival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorials', to='festivals.festival'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tutorials/images/'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='tutorials/pdfs/'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorials', to='villages.village'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorials', to='tutorials.tutorialcategory'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='video_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorialcategory',
            name='description',
            field=models.TextField(blank=True, default='No description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorialcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='TutorialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tutorials.tutorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TutorialEnrollment',
        ),
        migrations.DeleteModel(
            name='TutorialStep',
        ),
    ]
