# Generated by Django 5.2 on 2025-06-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_remove_tutorialstep_tutorial_alter_tutorial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tutorialcomment',
            options={'ordering': ['created_at']},
        ),
    ]
