# Generated by Django 5.2 on 2025-06-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('learner', 'Learner'), ('visitor', 'Visitor'), ('tutor', 'Tutor'), ('guide', 'Touristic Guide')], default='visitor', max_length=50, verbose_name='Role'),
        ),
    ]
