# Generated by Django 5.2 on 2025-06-28 15:23

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[users.models.validate_gmail], verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('learner', 'Learner'), ('visitor', 'Visitor'), ('tutor', 'Tutor'), ('guide', 'Touristic Guide')], max_length=50, verbose_name='Role'),
        ),
    ]
