# Generated by Django 5.2 on 2025-06-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('image', models.ImageField(upload_to='attractions/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Attraction',
                'verbose_name_plural': 'Attractions',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='LocalSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('image', models.ImageField(upload_to='local_sites/', verbose_name='Image')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Local Site',
                'verbose_name_plural': 'Local Sites',
            },
        ),
        migrations.CreateModel(
            name='TourActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Tour Activity',
                'verbose_name_plural': 'Tour Activities',
            },
        ),
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Tour Category',
                'verbose_name_plural': 'Tour Categories',
            },
        ),
        migrations.CreateModel(
            name='TourCulturalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cultural_experiences/', verbose_name='Image')),
                ('video', models.FileField(blank=True, null=True, upload_to='cultural_experiences/videos/', verbose_name='Video')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
                ('available_slots', models.PositiveIntegerField(default=0, verbose_name='Available Slots')),
                ('booked_slots', models.PositiveIntegerField(default=0, verbose_name='Booked Slots')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Tour Cultural Experience',
                'verbose_name_plural': 'Tour Cultural Experiences',
            },
        ),
        migrations.CreateModel(
            name='TourCulturalExperienceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='Booked At')),
                ('number_of_slots', models.PositiveIntegerField(default=1, verbose_name='Number of Slots')),
            ],
            options={
                'verbose_name': 'Tour Cultural Experience Booking',
                'verbose_name_plural': 'Tour Cultural Experience Bookings',
            },
        ),
        migrations.CreateModel(
            name='TourCulturalExperienceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(verbose_name='Rating')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Tour Cultural Experience Review',
                'verbose_name_plural': 'Tour Cultural Experience Reviews',
            },
        ),
        migrations.CreateModel(
            name='TourEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Tour Event',
                'verbose_name_plural': 'Tour Events',
            },
        ),
        migrations.CreateModel(
            name='TourEventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered At')),
            ],
            options={
                'verbose_name': 'Tour Event Registration',
                'verbose_name_plural': 'Tour Event Registrations',
            },
        ),
        migrations.CreateModel(
            name='TourFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(verbose_name='Feedback Text')),
                ('rating', models.PositiveIntegerField(verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Tour Feedback',
                'verbose_name_plural': 'Tour Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='TourGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('expertise', models.CharField(blank=True, max_length=255, verbose_name='Expertise')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
            ],
            options={
                'verbose_name': 'Tour Guide',
                'verbose_name_plural': 'Tour Guides',
            },
        ),
        migrations.CreateModel(
            name='TourItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Tour Itinerary',
                'verbose_name_plural': 'Tour Itineraries',
            },
        ),
        migrations.CreateModel(
            name='TourMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='tour_maps/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Tour Map',
                'verbose_name_plural': 'Tour Maps',
            },
        ),
        migrations.CreateModel(
            name='TourPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_photos/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Tour Photo',
                'verbose_name_plural': 'Tour Photos',
            },
        ),
        migrations.CreateModel(
            name='TourPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Duration (days)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Tour Plan',
                'verbose_name_plural': 'Tour Plans',
            },
        ),
        migrations.CreateModel(
            name='TourReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(verbose_name='Rating')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Tour Review',
                'verbose_name_plural': 'Tour Reviews',
            },
        ),
        migrations.CreateModel(
            name='TourSafetyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_tips', models.TextField(verbose_name='Safety Tips')),
                ('emergency_contacts', models.TextField(blank=True, verbose_name='Emergency Contacts')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Tour Safety Info',
                'verbose_name_plural': 'Tour Safety Infos',
            },
        ),
        migrations.CreateModel(
            name='TourTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='transport/', verbose_name='Image')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
            ],
            options={
                'verbose_name': 'Tour Transport',
                'verbose_name_plural': 'Tour Transports',
            },
        ),
        migrations.CreateModel(
            name='TourTransportBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Tour Transport Booking',
                'verbose_name_plural': 'Tour Transport Bookings',
            },
        ),
        migrations.CreateModel(
            name='TourWeatherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Average Temperature')),
                ('best_visit_season', models.CharField(blank=True, max_length=100, verbose_name='Best Visit Season')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Tour Weather Info',
                'verbose_name_plural': 'Tour Weather Infos',
            },
        ),
    ]
