# Generated by Django 5.2 on 2025-06-06 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourism', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attraction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attractions', to='tourism.category'),
        ),
        migrations.AddField(
            model_name='localsite',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='touractivity',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tourism.attraction'),
        ),
        migrations.AddField(
            model_name='touractivity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourculturalexperience',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_experiences', to='tourism.attraction'),
        ),
        migrations.AddField(
            model_name='tourculturalexperience',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourculturalexperiencebooking',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tourism.tourculturalexperience'),
        ),
        migrations.AddField(
            model_name='tourculturalexperiencebooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourculturalexperiencereview',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tourism.tourculturalexperience'),
        ),
        migrations.AddField(
            model_name='tourculturalexperiencereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toureventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tourism.tourevent'),
        ),
        migrations.AddField(
            model_name='toureventregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourfeedback',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tourism.attraction'),
        ),
        migrations.AddField(
            model_name='tourfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour_guide_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='touritinerary',
            name='attractions',
            field=models.ManyToManyField(blank=True, related_name='itineraries', to='tourism.attraction'),
        ),
        migrations.AddField(
            model_name='touritinerary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourmap',
            name='attractions',
            field=models.ManyToManyField(blank=True, related_name='maps', to='tourism.attraction'),
        ),
        migrations.AddField(
            model_name='tourmap',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourphoto',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tourism.attraction'),
        ),
        migrations.AddField(
            model_name='tourphoto',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='attractions',
            field=models.ManyToManyField(blank=True, to='tourism.attraction'),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='guide',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'guide'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tourism.attraction'),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toursafetyinfo',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_info', to='tourism.attraction'),
        ),
        migrations.AddField(
            model_name='toursafetyinfo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourtransportbooking',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tourism.tourtransport'),
        ),
        migrations.AddField(
            model_name='tourtransportbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourweatherinfo',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_info', to='tourism.attraction'),
        ),
        migrations.AddField(
            model_name='tourweatherinfo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
