# Generated by Django 5.2 on 2025-06-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localsite',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
