# Generated by Django 5.2 on 2025-06-26 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_initial'),
        ('villages', '0002_remove_localsite_village_alter_village_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingFamilyExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('can_host', models.PositiveIntegerField(default=1, help_text='How many tourists can be hosted')),
                ('live_cooking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_added', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_families', to='villages.village')),
            ],
        ),
        migrations.CreateModel(
            name='SharedTouristMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tourism/shared_media/')),
                ('video', models.FileField(blank=True, null=True, upload_to='tourism/shared_media/videos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_media', to='tourism.hostingfamilyexperience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialImmersionExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('host_family', models.CharField(blank=True, max_length=255)),
                ('activities', models.TextField(blank=True, help_text='Describe the activities involved')),
                ('live_cooking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_immersions_added', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_immersions', to='villages.village')),
            ],
        ),
        migrations.CreateModel(
            name='TourismActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourism_activities', to='tourism.hostingfamilyexperience')),
                ('immersion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourism_activities', to='tourism.socialimmersionexperience')),
            ],
        ),
        migrations.CreateModel(
            name='TouristComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tourism.hostingfamilyexperience')),
                ('immersion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tourism.socialimmersionexperience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TouristFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tourism.hostingfamilyexperience')),
                ('immersion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tourism.socialimmersionexperience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TouristicAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='tourism/attractions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attractions_added', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='villages.village')),
            ],
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tourreview',
            name='attraction',
        ),
        migrations.RemoveField(
            model_name='tourfeedback',
            name='attraction',
        ),
        migrations.RemoveField(
            model_name='touractivity',
            name='attraction',
        ),
        migrations.RemoveField(
            model_name='tourmap',
            name='attractions',
        ),
        migrations.RemoveField(
            model_name='toursafetyinfo',
            name='attraction',
        ),
        migrations.RemoveField(
            model_name='tourculturalexperience',
            name='attraction',
        ),
        migrations.RemoveField(
            model_name='tourphoto',
            name='attraction',
        ),
        migrations.RemoveField(
            model_name='tourweatherinfo',
            name='attraction',
        ),
        migrations.RemoveField(
            model_name='tourplan',
            name='attractions',
        ),
        migrations.RemoveField(
            model_name='touritinerary',
            name='attractions',
        ),
        migrations.RemoveField(
            model_name='localsite',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='touractivity',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='TourCategory',
        ),
        migrations.RemoveField(
            model_name='tourculturalexperience',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tourculturalexperiencereview',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='tourculturalexperiencebooking',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='tourculturalexperiencebooking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tourculturalexperiencereview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tourevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='toureventregistration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='toureventregistration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tourfeedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tourguide',
            name='user',
        ),
        migrations.RemoveField(
            model_name='touritinerary',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tourmap',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tourphoto',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='tourplan',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='tourreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='toursafetyinfo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tourtransportbooking',
            name='transport',
        ),
        migrations.RemoveField(
            model_name='tourtransportbooking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tourweatherinfo',
            name='created_by',
        ),
        migrations.AddField(
            model_name='sharedtouristmedia',
            name='immersion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_media', to='tourism.socialimmersionexperience'),
        ),
        migrations.AddField(
            model_name='touristfeedback',
            name='attraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tourism.touristicattraction'),
        ),
        migrations.AddField(
            model_name='touristcomment',
            name='attraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tourism.touristicattraction'),
        ),
        migrations.AddField(
            model_name='tourismactivity',
            name='attraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tourism.touristicattraction'),
        ),
        migrations.AddField(
            model_name='sharedtouristmedia',
            name='attraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_media', to='tourism.touristicattraction'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Attraction',
        ),
        migrations.DeleteModel(
            name='LocalSite',
        ),
        migrations.DeleteModel(
            name='TourActivity',
        ),
        migrations.DeleteModel(
            name='TourCulturalExperience',
        ),
        migrations.DeleteModel(
            name='TourCulturalExperienceBooking',
        ),
        migrations.DeleteModel(
            name='TourCulturalExperienceReview',
        ),
        migrations.DeleteModel(
            name='TourEvent',
        ),
        migrations.DeleteModel(
            name='TourEventRegistration',
        ),
        migrations.DeleteModel(
            name='TourFeedback',
        ),
        migrations.DeleteModel(
            name='TourGuide',
        ),
        migrations.DeleteModel(
            name='TourItinerary',
        ),
        migrations.DeleteModel(
            name='TourMap',
        ),
        migrations.DeleteModel(
            name='TourPhoto',
        ),
        migrations.DeleteModel(
            name='TourPlan',
        ),
        migrations.DeleteModel(
            name='TourReview',
        ),
        migrations.DeleteModel(
            name='TourSafetyInfo',
        ),
        migrations.DeleteModel(
            name='TourTransport',
        ),
        migrations.DeleteModel(
            name='TourTransportBooking',
        ),
        migrations.DeleteModel(
            name='TourWeatherInfo',
        ),
    ]
